### ISSUE TITLE
Automatic Size issue on initial load

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf-previewer#118]
When first loading, in some cases the PDF is getting cut off and not displaying correctly. Using the zoom control fixes this.

See the video for full details

https://www.loom.com/share/53560e3b178844019191fa699718b314

**Comment by jakejackson1** [comment]
To add to this, this bug appears to occur when multiple PDFs are configured on a single form.

![Screen Shot 2021-11-09 at 3 24 29 pm](https://user-images.githubusercontent.com/2918419/140865057-306501e3-f609-4a4d-8bde-5bd0711434d9.png)

This became apparent when I started filling out content in my test form and got Rubix styling instead of Zadani. These two screenshots are of the same Previewer. Without a page reload if I zoom out slightly I get the correct Zadani PDF, but on initial refresh I get the Rubix one.

<img width="698" alt="Screen Shot 2021-11-09 at 3 57 50 pm" src="https://user-images.githubusercontent.com/2918419/140865126-18470050-c07f-4977-804a-abc809f6ca3f.png">

<img width="703" alt="Screen Shot 2021-11-09 at 3 57 55 pm" src="https://user-images.githubusercontent.com/2918419/140865139-11f400f5-8f23-4806-95d2-e341d783aa51.png">

**Comment by jakejackson1** [comment]
The plot thickens. The final piece of the puzzle is I have two Previewer fields on the same page: one setup with PDF 1 (Zadani) and one setup with PDF2 (Rubix). Looks like the second Previewer is effecting the first, which obviously shouldn't happen.

**Comment by debbieellis7** [comment]
Should be auto fixed on PR #120
