### ISSUE TITLE
Preview Error not showing up to end user

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf-previewer#22]
The server responds `{"error":"Requested PDF could not be found"}` when calling `/wp-json/gravity-pdf-previewer/v1/pdf/5a2f7490ce6f6` but an error isn't shown.

**Comment by jakejackson1** [comment]
The response gets passed straight to our viewer so we cannot do anything with it.

We could look at sending a "PDF Not Found" document to the viewer instead...

**Comment by HQ19** [comment]
Has it been fixed already? I also have the same problem with generating preview of PDF. End user sees text "There was a problem loading the preview." and button to reload the file.

**Comment by jakejackson1** [comment]
Hi @mardrof. There's a number of reasons for the end using seeing the text "There was a problem loading the preview", but this issue isn't one of them (it's specifically about that text not showing up, when it really should). 

If you are experiencing a problem, [please get in touch with our support team](https://gravitypdf.com/support/) and we'll be happy to help.

**Comment by debbieellis7** [comment]
We show this screen for PDF generation error, @jakejackson1
![1](https://user-images.githubusercontent.com/10412650/149492440-de6a3968-f613-4020-8fad-a58bd344f195.jpg)

**Comment by debbieellis7** [comment]
Closing this issue as error handling for PDF download endpoint has been added already under latest development branch.
