### ISSUE TITLE
Preview not showing formatted text

### ISSUE THREAD

**Issue by michieloosterling** [GravityPDF/gravity-pdf-previewer#43]
Don't know if this is intended behaviour or not, but a PDF preview field does not render formatted text as entered into a rich text field in the form. For example, text that has been bolded or underlined. I suspect this has to do with PDF.js, but I'm not sure, as it doesn't look like the object containing the data from all available field has this information to begin with.

Is this behaviour intended, and if so, is there a workaround?

**Comment by michieloosterling** [comment]
My pleasure. The patch does not fix the issue on my side, tested on three browsers 2 different machines, just in case cacheing was an issue.
To give you an idea, we have a form with a bunch of regular fields (name, address, phone number, etc) that also includes a textarea that has been marked as allowing rich text under the advanced tab of that particular field's settings. When the saved form is tested on the frontend or by previewing the form straight from the GravityForms admin section, the live updated PDF preview will return plain text. Also tried by stripping the form down to just the rich text field, with the same results.
Spitting out the 'raw' object holding the (temporary) form data also does not show any type of styling or tags being passed along.

Interestingly, the PDF that's generated by Gravity PDF when a form is submitted DOES contain the styled text, and will correctly display bold, italics, underlines, links, etc.

**Comment by jakejackson1** [comment]
This issue is now resolved in Previewer version 1.2.1.
